package com.example.ihb.aleksandryurkovskiy.data.storage.models;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TITLES".
*/
public class TitleDao extends AbstractDao<Title, Long> {

    public static final String TABLENAME = "TITLES";

    /**
     * Properties of entity Title.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CharacterRemoteId = new Property(1, Long.class, "characterRemoteId", false, "CHARACTER_REMOTE_ID");
        public final static Property Title = new Property(2, String.class, "title", false, "TITLE");
    };

    private DaoSession daoSession;

    private Query<Title> character_TitlesQuery;

    public TitleDao(DaoConfig config) {
        super(config);
    }
    
    public TitleDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TITLES\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"CHARACTER_REMOTE_ID\" INTEGER," + // 1: characterRemoteId
                "\"TITLE\" TEXT);"); // 2: title
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TITLES\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Title entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long characterRemoteId = entity.getCharacterRemoteId();
        if (characterRemoteId != null) {
            stmt.bindLong(2, characterRemoteId);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Title entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long characterRemoteId = entity.getCharacterRemoteId();
        if (characterRemoteId != null) {
            stmt.bindLong(2, characterRemoteId);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
    }

    @Override
    protected final void attachEntity(Title entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Title readEntity(Cursor cursor, int offset) {
        Title entity = new Title( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // characterRemoteId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // title
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Title entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCharacterRemoteId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Title entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Title entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "titles" to-many relationship of Character. */
    public List<Title> _queryCharacter_Titles(Long characterRemoteId) {
        synchronized (this) {
            if (character_TitlesQuery == null) {
                QueryBuilder<Title> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.CharacterRemoteId.eq(null));
                character_TitlesQuery = queryBuilder.build();
            }
        }
        Query<Title> query = character_TitlesQuery.forCurrentThread();
        query.setParameter(0, characterRemoteId);
        return query.list();
    }

}
